name: at2
description: AutoTriage 2.
version: 0.0.1
repository: https://github.com/tytydraco/at2

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  very_good_analysis: ^10.0.0

executables:
  at2: at2